apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-prod/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: gdvn/auth
      context: src/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gdvn/user
      context: src/user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gdvn/company
      context: src/company
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: gdvn/allowance
      context: src/allowance
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .