apiVersion: apps/v1
kind: Deployment
metadata:
  name: allowance-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allowance-mongo
  template:
    metadata:
      labels:
        app: allowance-mongo
    spec:
      containers:
        - name: allowance-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: allowance-mongo-srv
spec:
  type: NodePort
  selector:
    app: allowance-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
