apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: gdvn/company
          env:
            - name: MONGO_URI
              value: 'mongodb://company-mongo-srv:27017/company'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: gdvn-system
---
apiVersion: v1
kind: Service
metadata:
  name: company-srv
spec:
  selector:
    app: company
  ports:
    - name: company
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort